apiVersion: v1
kind: Secret
metadata:
  name: labs-db-secret
type: Opaque
stringData:
  PGHOST: bGFiLW1hbmFnZXItZGJzLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  PGUSER: dXNlcg==
  PGPORT: NTQzMg==
  PGDATABASE: bGFicy1kYg==
  PGPASSWORD: R2VzbG8xMjM=
