apiVersion: v1
kind: Secret
metadata:
  name: labs-db-secret
type: Opaque
stringData:
  PGHOST: lab-manager-dbs.postgres.database.azure.com
  PGUSER: user
  PGPORT: 5432
  PGDATABASE: labs-db
  PGPASSWORD: Geslo123
